<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-6JJE3KO" ignored="0" name="ChromeTest" tests="4" failures="1" timestamp="25 Apr 2020 06:40:13 GMT" time="0.612" errors="0">
  <testcase name="m1" time="0.015" classname="com.Testingshastra.Listeners.RegrssionTests"/>
  <testcase name="m2" time="0.002" classname="com.Testingshastra.Listeners.RegrssionTests"/>
  <testcase name="m3" time="0.002" classname="com.Testingshastra.Listeners.RegrssionTests">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at com.Testingshastra.Listeners.RegrssionTests.m3(RegrssionTests.java:24)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- m3 -->
  <testcase name="m4" time="0.001" classname="com.Testingshastra.Listeners.RegrssionTests"/>
</testsuite> <!-- ChromeTest -->
